const copy = {
  en: {
    lang: "PT",
    services: "Services",
    fleet: "Fleet",
    reviews: "Reviews",
    faq: "FAQ",
    how: "How it works",
    privacy: "Privacy",
    book: "Book now",
    whatsapp: "WhatsApp",
    eyebrow: "Algarve · Lisbon · Porto",
    h1: "Reliable rides that get you there safely and on time.",
    lead: "Airport transfers, golf, local journeys and private tours. Book in the app, choose the car, and confirm with Nuno on WhatsApp.",
    heroCap: "Model X · stand-in until your photos are in",
    sTitle: "Four ways to ride",
    sSub: "The same services as blacktaxi.pt, booked in the app.",
    airport: "Airport transfer",
    airportP: "Exclusive transfers for Faro, Lisbon and Porto. Flight tracking, and a name sign in arrivals when you want it.",
    golf: "Golf transfer",
    golfP: "A missed tee time is a lost opportunity. We time the car to the clubhouse so you arrive with room to warm up.",
    local: "Local journey",
    localP: "Point A to point B should be the easy part of the day. Coast, city and hotel to hotel.",
    tour: "Private tour",
    tourP: "Every moment is yours. The car and the day are arranged for you, across Portugal and into Spain on request.",
    howTitle: "How booking works",
    howSub: "No payment in the app. The quote is confirmed on WhatsApp.",
    st1: "Pin the addresses",
    st1p: "Search pickup and drop-off as you would in Maps. Now, or a date and time. One way or return.",
    st2: "People, bags, seats",
    st2p: "Passengers, hand luggage and checked luggage start at zero. Add child seats and a note if you need them.",
    st3: "Choose the car",
    st3p: "Model X, Model 3, V-Class, Vito, a standard car, or a special request. A named vehicle may cost more.",
    st4: "Confirm on WhatsApp",
    st4p: "The app opens a message to Nuno with the reference, route, bags and flight number. Nothing is charged in the app.",
    st1s: "Pickup and drop-off, now or later.",
    st2s: "Luggage starts at zero. Add child seats.",
    st3s: "A named car may cost more.",
    st4s: "Nuno confirms. Nothing is charged in the app.",
    xnote: "With 5 or 6 people the boot is tight.",
    fTitle: "The fleet",
    fSub: "Look at the cars in the app, then choose one while you book. If you do not mind which, leave a special request and the team will assign it.",
    x: "Tesla Model X",
    xp: "VIP · 6 passengers",
    m3: "Tesla Model 3",
    m3p: "4 passengers",
    v: "Mercedes V-Class",
    vp: "7 passengers",
    vito: "Mercedes Vito",
    vitop: "8 passengers",
    std: "Standard",
    stdp: "4, 6 or 8 passengers",
    special: "Special request",
    specialp: "Tell us what you need. The final price is confirmed on WhatsApp.",
    faqTitle: "Good to know",
    k1: "24/7",
    k1p: "Airport, coast and city, including a late flight.",
    k2: "Flight tracking",
    k2p: "Add the flight number. A name sign in arrivals if you want it.",
    k3: "Child seats",
    k3p: "Ask in the form. Hand luggage and checked luggage start at zero.",
    k4: "No payment in the app",
    k4p: "The quote is confirmed with Nuno on WhatsApp.",
    fq1: "How do I book?",
    fa1: "Open the app, pin pickup and drop-off, add people, bags and a car, then send the WhatsApp message. Nothing is charged in the app.",
    fq2: "What if my flight is late?",
    fa2: "Put the flight number in the note. We track the flight. Message WhatsApp if the plan changes.",
    fq3: "Can I choose the car?",
    fa3: "Yes. Model X, Model 3, V-Class, Vito, a standard car, or a special request. A named car may cost more. If you do not mind, the team assigns one.",
    fq4: "Where do you go?",
    fa4: "Algarve, Lisbon and Porto. Faro, Lisbon and Porto airports. Spain on request, including longer runs such as Lagos to Seville.",
    fq5: "How do I change a ride?",
    fa5: "Reply on the same WhatsApp chat with the reference. We do not publish a cancellation fee here.",
    rTitle: "What customers say",
    rSub: "Reviews name Nuno and his team.",
    q1: "I’ve used Nuno and his team many times — airport pickups and longer routes like Lagos to Seville. Faultless every time.",
    q2: "Nuno is always our first call whenever we’re heading to Portimão. Incredibly punctual, and goes above and beyond.",
    q3: "Faro to Lagos in style. We were a bit late off the plane and it wasn’t a problem.",
    q4: "We use Black Taxi whenever we come to the Algarve. Always on time, always courteous.",
    read: "Read 23 Tripadvisor reviews",
    google: "Review on Google",
    trip: "Review on Tripadvisor",
    aboutTitle: "A trusted ride partner",
    about: "Black Taxi blends safety and comfort in every journey. From a prompt airport transfer to a private day in Sintra, the car is yours. Available 24/7 across the Algarve, Lisbon and Porto. Spain on request.",
    coastCap: "Coast road, Algarve",
    ctaTitle: "Book the ride in the app.",
    cta: "Pickup, drop-off, time, luggage and car. Then WhatsApp confirms it.",
    foot: "Exclusive transfers and private tours across Portugal and Spain.",
    draft: "Draft site for the booking app. Not published. blacktaxi.pt stays live until you switch.",
    ph1: "Privacy",
    phLead: "Black Taxi uses your name, phone and trip details only to confirm the ride on WhatsApp.",
    ph2: "There is no account and no payment in the app. We do not store a card. The message you send includes the reference, pickup, drop-off, time, passengers, luggage, child seats, vehicle, flight number and notes.",
    ph3: "Contact info@blacktaxi.pt or +351 928 488 984 to ask about a ride or to have a request deleted from the chat.",
    back: "Back"
  },
  pt: {
    lang: "EN",
    services: "Serviços",
    fleet: "Frota",
    reviews: "Avaliações",
    faq: "FAQ",
    how: "Como funciona",
    privacy: "Privacidade",
    book: "Reservar",
    whatsapp: "WhatsApp",
    eyebrow: "Algarve · Lisboa · Porto",
    h1: "Viagens fiáveis, seguras e a horas.",
    lead: "Transfers de aeroporto, golfe, trajetos locais e tours privados. Reserve na app, escolha o carro e confirme com o Nuno no WhatsApp.",
    heroCap: "Model X · foto provisória até às vossas",
    sTitle: "Quatro formas de viajar",
    sSub: "Os mesmos serviços de blacktaxi.pt, reservados na app.",
    airport: "Transfer de aeroporto",
    airportP: "Transfers exclusivos para Faro, Lisboa e Porto. Seguimos o voo e levamos placa com o nome, se quiser.",
    golf: "Transfer de golfe",
    golfP: "Perder o tee time é perder a volta. O carro chega a tempo do aquecimento no clube.",
    local: "Trajeto local",
    localP: "Ir do ponto A ao B deve ser a parte fácil do dia. Costa, cidade e hotel a hotel.",
    tour: "Tour privado",
    tourP: "Cada momento é seu. O carro e o dia ficam tratados, em Portugal e em Espanha a pedido.",
    howTitle: "Como funciona a reserva",
    howSub: "Não há pagamento na app. O preço confirma-se no WhatsApp.",
    st1: "Marque os endereços",
    st1p: "Pesquisa de recolha e destino, como no mapa. Agora, ou data e hora. Ida ou ida e volta.",
    st2: "Pessoas, malas, cadeiras",
    st2p: "Passageiros, mala de mão e mala de porão começam em zero. Junte cadeiras de criança e uma nota se precisar.",
    st3: "Escolha o carro",
    st3p: "Model X, Model 3, V-Class, Vito, um standard, ou um pedido especial. Um carro específico pode custar mais.",
    st4: "Confirme no WhatsApp",
    st4p: "A app abre uma mensagem ao Nuno com a referência, a rota, as malas e o número do voo. Nada é cobrado na app.",
    st1s: "Recolha e destino, agora ou mais tarde.",
    st2s: "As malas começam em zero. Junte cadeiras.",
    st3s: "Um carro específico pode custar mais.",
    st4s: "O Nuno confirma. Nada é cobrado na app.",
    xnote: "Com 5 ou 6 pessoas a mala fica apertada.",
    fTitle: "A frota",
    fSub: "Veja os carros na app e escolha um ao reservar. Se não tiver preferência, deixe um pedido especial e a equipa atribui o carro.",
    x: "Tesla Model X",
    xp: "VIP · 6 passageiros",
    m3: "Tesla Model 3",
    m3p: "4 passageiros",
    v: "Mercedes V-Class",
    vp: "7 passageiros",
    vito: "Mercedes Vito",
    vitop: "8 passageiros",
    std: "Standard",
    stdp: "4, 6 ou 8 passageiros",
    special: "Pedido especial",
    specialp: "Diga o que precisa. O preço final confirma-se no WhatsApp.",
    faqTitle: "Bom saber",
    k1: "24 horas",
    k1p: "Aeroporto, costa e cidade, incluindo um voo atrasado.",
    k2: "Seguimento do voo",
    k2p: "Indique o número do voo. Placa com o nome nas chegadas, se quiser.",
    k3: "Cadeiras de criança",
    k3p: "Peça no formulário. Mala de mão e mala de porão começam em zero.",
    k4: "Sem pagamento na app",
    k4p: "O preço confirma-se com o Nuno no WhatsApp.",
    fq1: "Como reservo?",
    fa1: "Abra a app, marque recolha e destino, junte pessoas, malas e o carro, e envie a mensagem de WhatsApp. Nada é cobrado na app.",
    fq2: "E se o voo atrasar?",
    fa2: "Ponha o número do voo na nota. Seguimos o voo. Escreva no WhatsApp se o plano mudar.",
    fq3: "Posso escolher o carro?",
    fa3: "Sim. Model X, Model 3, V-Class, Vito, um standard, ou um pedido especial. Um carro específico pode custar mais. Se não tiver preferência, a equipa atribui.",
    fq4: "Onde vão?",
    fa4: "Algarve, Lisboa e Porto. Aeroportos de Faro, Lisboa e Porto. Espanha a pedido, incluindo percursos longos como Lagos–Sevilha.",
    fq5: "Como altero uma viagem?",
    fa5: "Responda na mesma conversa de WhatsApp com a referência. Não publicamos aqui uma taxa de cancelamento.",
    rTitle: "O que dizem os clientes",
    rSub: "As avaliações falam do Nuno e da equipa.",
    q1: "Já usei o Nuno e a equipa muitas vezes — recolhas no aeroporto e rotas longas, como Lagos–Sevilha. Impecável.",
    q2: "O Nuno é sempre a primeira chamada quando vamos para Portimão. Pontual e disponível.",
    q3: "Faro–Lagos em grande. Saímos atrasados do avião e não foi problema.",
    q4: "Usamos a Black Taxi sempre que vimos ao Algarve. Sempre a horas, sempre corretos.",
    read: "Ler 23 avaliações no Tripadvisor",
    google: "Avaliar no Google",
    trip: "Avaliar no Tripadvisor",
    aboutTitle: "Um parceiro de confiança",
    about: "A Black Taxi junta segurança e conforto em cada viagem. De um transfer de aeroporto a um dia privado em Sintra, o carro é seu. Disponível 24 horas no Algarve, Lisboa e Porto. Espanha a pedido.",
    coastCap: "Estrada da costa, Algarve",
    ctaTitle: "Reserve a viagem na app.",
    cta: "Recolha, destino, hora, malas e carro. Depois o WhatsApp confirma.",
    foot: "Transfers exclusivos e tours privados em Portugal e Espanha.",
    draft: "Site de rascunho para a app de reservas. Não publicado. O blacktaxi.pt continua no ar até decidir a troca.",
    ph1: "Privacidade",
    phLead: "A Black Taxi usa o nome, o telefone e os dados da viagem só para confirmar o serviço no WhatsApp.",
    ph2: "Não há conta nem pagamento na app. Não guardamos cartão. A mensagem inclui a referência, recolha, destino, hora, passageiros, malas, cadeiras, veículo, voo e notas.",
    ph3: "Contacte info@blacktaxi.pt ou +351 928 488 984 para perguntar por uma viagem ou pedir que o pedido seja apagado da conversa.",
    back: "Voltar"
  }
};

function apply(lang) {
  const t = copy[lang] || copy.en;
  document.documentElement.lang = lang === "pt" ? "pt" : "en";
  document.querySelectorAll("[data-i]").forEach((el) => {
    const key = el.getAttribute("data-i");
    if (t[key]) el.textContent = t[key];
  });
  const btn = document.querySelector("[data-lang]");
  if (btn) btn.textContent = t.lang;
  localStorage.setItem("bt-lang", lang);
}

document.addEventListener("click", (e) => {
  const btn = e.target.closest("[data-lang]");
  if (!btn) return;
  const next = document.documentElement.lang === "pt" ? "en" : "pt";
  apply(next);
});

apply(localStorage.getItem("bt-lang") || "en");
